# .scrutinizer.yml
checks:
  php:
    code_rating: true
    duplication: true

tools:
    php_code_sniffer: true
    php_sim: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
