tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - 'tests/*'

checks:
    php:
        verify_property_names: true
        verify_argument_usable_as_reference: true
        variable_existence: true
        psr2_switch_declaration: true
        psr2_class_declaration: true
        verify_access_scope_valid: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true

