language:
  php

php:
  - 7.4
  - 7.3
    
before_install:
  - composer selfupdate
  - sudo pip install codecov

install:
  - composer install --no-interaction

script:
  - phpunit --colors --coverage-clover=coverage.xml tests

after_success:
  - codecov
