language:
  php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm
    
before_install:
  - composer selfupdate
  - sudo pip install codecov

install:
  - composer install --dev --no-interaction

script:
  - phpunit --colors tests/dHttpTest --coverage-clover=coverage.xml

after_success:
  - codecov
