language:
  php

php:
  - 5.3
  - 5.4
  - 5.5
  
matrix:
  allow_failures:
    - php: hhvm
    
before_install:
  - composer selfupdate
  - mkdir -p build/logs

install:
  - composer install --dev --prefer-source

script:
  - phpunit --colors tests/dHttpTest
  
after_script:
  - php vendor/bin/coveralls
